#!/bin/bash
# USAGE: ./scripts/get-coreos
# USAGE: ./scripts/get-coreos channel version dest
IP=${1:-"172\.16\.73\.121"}
DEST_DIR=${2:-"$PWD/examples_own/"}
# find DEST_DIR  -type f -exec sed -i 's/matchbox\.foo/172\.16\.73\.121/g' {} \;
rm -rf $DEST_DIR
cp -rf $PWD/examples $DEST_DIR 
find $DEST_DIR -type f -exec sed -i "s/matchbox\.foo/$IP/g" {} \;
